apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "letsencrypt-prod"
spec:
  acme:
    email: "onyekagodonu@yahoo.com"
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    # To use the production environment, use the following line instead:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: "letsencrypt-prod"
    solvers:
    - selector:
        dnsZones:
          - "onyeka.online"
      dns01:
        route53:
          region: "us-east-2"
          hostedZoneID: "Z06571531LJLYOK9JTKPQ"
